apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chproxy.fullname" . }}
  labels:
    {{- include "chproxy.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{ .Values.config | nindent 4 }}