apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chproxy.fullname" . }}
  labels:
    {{- include "chproxy.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "chproxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ .Values.config | sha256sum | trunc 8 }} 
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}        
      {{- end }}
      labels:
        {{- include "chproxy.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "chproxy.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            {{- range .Values.service.ports }}
            - containerPort: {{ .port }}
              protocol: TCP
              name: {{ .name }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /metrics
              port: {{.Values.livenessProbePort}}
          readinessProbe:
            httpGet:
              path: /metrics
              port: {{.Values.readinessProbePort}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/chproxy
              readOnly: true
          command: 
            - /chproxy
            - --config
            - /etc/chproxy/config.yaml
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            defaultMode: 0600
            name: {{ include "chproxy.fullname" . }}