name: Lint Code Base
on: pull_request
jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Lint Code Base
        uses: docker://github/super-linter:v3.12.0
        env:
          VALIDATE_YAML: false
          VALIDATE_BASH: false
          VALIDATE_KUBERNETES_KUBEVAL: false
          VALIDATE_PYTHON: false
          VALIDATE_PYTHON_FLAKE8: false
          VALIDATE_PYTHON_BLACK: false
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}